# --- V17 Geometric Configs ---
NUM_BINS = 72
DEGREES_PER_BIN = 360 / NUM_BINS
MIN_INK_PER_BIN = 2
MARKED_THRESHOLD_DEG = 180
BLANK_THRESHOLD_DEG = 90
LOCAL_PAD = 15
OUTER_RADIUS = 32
GLOBAL_PAD = 20
MERGE_THRESHOLD = 15.0
EXTREMES_REJECT_THRESHOLD = 50.0

# Fallback defaults
CHECKBOX_INNER_MARGIN = 5
HSV_SATURATION_THRESHOLD = 40

DIFF_THRESHOLD = 30
GAUSS_KERNEL = (3, 3)
CLOSE_KERNEL_SIZE = 5
CLOSE_ITERATIONS = 2
LOCAL_CLOSE_KERNEL = 3
LOCAL_CLOSE_ITERS = 1
